(cl:defpackage gps_agent_pkg-msg
  (:use )
  (:export
   "<POSITIONCOMMAND>"
   "POSITIONCOMMAND"
   "<RELAXCOMMAND>"
   "RELAXCOMMAND"
   "<TRIALCOMMAND>"
   "TRIALCOMMAND"
   "<DATAREQUEST>"
   "DATAREQUEST"
   "<TFOBSDATA>"
   "TFOBSDATA"
   "<TFACTIONCOMMAND>"
   "TFACTIONCOMMAND"
   "<CAFFEPARAMS>"
   "CAFFEPARAMS"
   "<LINGAUSSPARAMS>"
   "LINGAUSSPARAMS"
   "<TFPARAMS>"
   "TFPARAMS"
   "<SAMPLERESULT>"
   "SAMPLERESULT"
   "<CONTROLLERPARAMS>"
   "CONTROLLERPARAMS"
   "<DATATYPE>"
   "DATATYPE"
  ))

